auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Blog_HZ.Jun
url: http://hzj1989a.github.io/
feed: /atom.xml
author_info: <a href="http://hzj1989a.github.io/">HZ.Jun</a>
