auto: true

markdown: rdiscount
highlighter: true
paginate: 8
permalink: /:title

title: Blog_HZ.Jun
url: http://Nh-touch.github.io/
feed: /atom.xml
author_info: <a href="http://Nh-touch.github.io/">HZ.Jun</a>
encoding: utf-8
